services:
  garage:
    image: dxflrs/garage:v2.3.0
    command:
      - /garage
      - server
      - --single-node
      - --default-bucket
    environment:
      - GARAGE_S3_API_URL=$GARAGE_S3_API_URL
      - GARAGE_WEB_URL=$GARAGE_WEB_URL
      - GARAGE_ADMIN_URL=$GARAGE_ADMIN_URL
      - GARAGE_RPC_SECRET=$SERVICE_HEX_64_RPCSECRET
      - GARAGE_ADMIN_TOKEN=$SERVICE_PASSWORD_GARAGE
      - GARAGE_METRICS_TOKEN=$SERVICE_PASSWORD_GARAGEMETRICS
      - GARAGE_ALLOW_WORLD_READABLE_SECRETS=true
      - GARAGE_DEFAULT_ACCESS_KEY=$GARAGE_DEFAULT_ACCESS_KEY
      - GARAGE_DEFAULT_SECRET_KEY=$GARAGE_DEFAULT_SECRET_KEY
      - GARAGE_DEFAULT_BUCKET=usage-monitor
      - RUST_LOG=garage=info
    volumes:
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
      - type: bind
        source: ./garage.toml
        target: /etc/garage.toml
    healthcheck:
      test:
        - CMD
        - /garage
        - stats
        - -a
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  garage-meta:
  garage-data:
